version: "3.9"
services:
  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"

  email_service:
    build: ./email_service
    container_name: email_service
    ports:
      - "8001:8000"

  folder_service:
    build: ./folder_service
    container_name: folder_service
    ports:
      - "8002:8000"
