version: "3.9"
services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  user_service:
    build: ./user_service
    container_name: user_service
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:secret@postgres_db:5432/user_db

  email_service:
    build: ./email_service
    container_name: email_service
    ports:
      - "8001:8000"

  folder_service:
    build: ./folder_service
    container_name: folder_service
    ports:
      - "8002:8000"

volumes:
  db_data:
